name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: With pytest for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: 🛠️ Set up Python
        uses: actions/setup-python@v5.0.0
        id: python
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_test.txt

      - name: 📦 Install requirements
        run: |
          scripts/install/frontend
          scripts/install/pip_packages --requirement requirements_test.txt

      - name: 🏃 Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest

      - name: 📤 Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          scripts/coverage
          curl -sfSL https://codecov.io/bash | bash -

  legacy:
    name: With pytest with Home Assistant 2023.6.0
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: 🛠️ Set up Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_test.txt

      - name: 📦 Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_test.txt
          scripts/install/core
          scripts/install/frontend

      - name: 🏃 Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest

  core_dev:
    name: With pytest with Home Assistant dev
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: 🛠️ Set up Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_test.txt

      - name: 📦 Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_test.txt
          scripts/install/core_dev
          scripts/install/frontend

      - name: 🏃 Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest
